name: Release zfs-cleaner binaries

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64,arm64]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build release
        uses: wangyoucao577/go-release-action@v1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz"
          project_path: "."
          binary_name: "zfs-cleaner"
          extra_files: LICENSE README.md
          sha256sum: true
          ldflags: "-X main.version=${{ github.ref_name }}"
